In [2]:
# 1ª questão:
import numpy as np # importando a biblioteca numpy
np.__version__

'1.20.1'

2ª questão:
- Vetorização é quando nos aplicamos alguma função a algum um array, sem usar estruturas de repetição;
- Broadcast e a técnica de relacionar elemento por elemento na operação de dois vetores.

3ª questão:

 Listas:
- Mutáveis;
- Ordenadas;
- Heterogêneas, tem capacidade de guardar mais de um tipo;
- Indexada por posição (Ex.: "0, 1, 2..." tendo cada item da lista indexada em uma dessas possições de forma ordenada); 
- Delimitada por colchetes [];
- Não podem ser feitas operações com os itens da lista.

Dicionários:
- Mutáveis, assim como as listas;
- Não ordenados;
- Heterogêneos, tem capacidade de guardar mais de um tipo, assim como as listas;
- Indexada por chaves (Cada item da lista possui uma 'chave', que serve da mesma forma que as posições da lista servem para os itens da lista, ou seja, para chamar um dos itens, deve-se usar a chave que identifica aquele item. A diferença é que essa chave deve ser dita na construção do dicionário, e não tem a necessidade de serem ordenados como a lista.) ;
- Delimitada por chaves { };
- Diferentes da lista, os itens pertencentes ao dicionário podem ser operados.

Array numpy herda algumas características pertencentes às listas e aos dicionários. Como por exemplo:
- Mutável e Heterogêneo, como ambos os outros são;
- Assim como os dicionários, pode ser feito operações com os itens pertencentes ao vetor.

Porém, sobre a questão de organização, pode ser feita indexação por chave, como é feito nos dicionários e pode quando não é especificado chave, automaticamente indexa de forma ordenada como ocorre nas listas.

In [4]:
# 4ª questão:
arr = [[1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14], [5, 10, 15]]
novo_arr = np.array(arr)
novo_arr

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [3]:
# 5ª questão, letra A:
arr = np.linspace(1,20,10)
arr

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [5]:
# 5ª questão, letra c:
arr = [[1, 0, 0],[0, 2, 0],[0, 0, 3]]
novo_arr = np.array(arr)
novo_arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])